export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const GET_USERDATA = 'GETUSERDATA';
export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_ERROR = 'GET_USERDATA_ERROR';

export const GET_RECORDDATA = 'GET_RECORDDATA';
export const GET_RECORDDATA_SUCCESS = 'GET_RECORDDATA_SUCCESS';
export const GET_RECORDDATA_ERROR = 'GET_RECORDDATA_ERROR';

export const POST_RECORD = 'POST_RECORD';
export const POST_RECORD_SUCCESS = 'POST_RECORD_SUCCESS';
export const POST_RECORD_ERROR = 'POST_RECORD_ERROR';

export const UPDATE_RECORD = 'UPDATE_RECORD';
export const UPDATE_RECORD_SUCCESS = 'UPDATE_RECORD_SUCCESS';
export const UPDATE_RECORD_ERROR = 'UPDATE_RECORD_ERROR';

export const DELETE_RECORD = 'DELETE_RECORD';
export const DELETE_RECORD_SUCCESS = 'DELETE_RECORD_SUCCESS';
export const DELETE_RECORD_ERROR = 'DELETE_RECORD_ERROR';

export const LOG_OUT = "LOG_OUT";